from typing import Literal

type Role = Literal[
    "system",
    "developer",
    "user",
    "assistant",
    "tool",
]
type StopReason = Literal[
    "completed",
    "stop",
    "length",
    "content_filter",
    "tool_calls",
    "insufficient_system_resource",
    "other",
    "language",
    "blocklist",
    "prohibited_content",
    "spii",
    "malformed_function_call",
    "unexpected_tool_call",
    "recitation",
    "no_image",
    "cancelled",
    "failed",
    "in_progress",
    "incomplete",
    "queued",
]

STOP_REASON_ALIASES: dict[str, StopReason] = {
    "completed": "completed",
    "stop": "stop",
    "end_turn": "stop",
    "stop_sequence": "stop",
    "length": "length",
    "max_tokens": "length",
    "content_filter": "content_filter",
    "safety": "content_filter",
    "image_safety": "content_filter",
    "tool_calls": "tool_calls",
    "function_call": "tool_calls",
    "tool_use": "tool_calls",
    "insufficient_system_resource": "insufficient_system_resource",
    "other": "other",
    "pause_turn": "other",
    "language": "language",
    "blocklist": "blocklist",
    "prohibited_content": "prohibited_content",
    "image_prohibited_content": "prohibited_content",
    "spii": "spii",
    "malformed_function_call": "malformed_function_call",
    "unexpected_tool_call": "unexpected_tool_call",
    "recitation": "recitation",
    "image_recitation": "recitation",
    "image_other": "other",
    "no_image": "no_image",
    "cancelled": "cancelled",
    "failed": "failed",
    "in_progress": "in_progress",
    "incomplete": "incomplete",
    "queued": "queued",
}
